#!/bin/bash
 
set -e
 
case "$1" in
   remove|purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
      rm -rf ~/.horus/
   ;;
   *)
      echo "postrm called with unknown argument \`\$1'" >&2
      exit 1
   ;;
esac

exit 0